### PR TITLE
Fix asterisk-11.20.0 compilation

### PR DESCRIPTION
**Pull request by dkgroot**
Based on FreePBX Ports Collection

### CODE REVIEW

**Comment by jrmarino** [comment]
okay.  There was no reason to change STATUS but the impact is minimal so I'll take the whole request, thanks.

**Comment by jrmarino** [comment]
PORTS_OPTIONS is not getting redefined so it's not building.  It probably requires :N modification (which I will attempt)

**Comment by jrmarino** [comment]
i think the use of <bsd.port.pre.mk> is breaking this, it's going to require a makefile diff

**Comment by dkgroot** [comment]
It seems to work fine inside dports. I only wanted to change the default value the compiler being used (to base instead of ports/gcc. Should i make a change, or has this already gone through ?

**Comment by jrmarino** [comment]
I suspect you saved your options.  DADHI was forced on no matter what.  It's only possible not to have it if options set manually.

**Comment by dkgroot** [comment]
BTW: Changing the defaults was not really required. So if you like, we can remove the line completely (maybe better)

**Comment by jrmarino** [comment]
it is required.  asterisk11 cannot have dahdi as an option.

I did assume you had a reason for the change

**Comment by dkgroot** [comment]
I wanted to change the default compiler (which get's set to ports/gcc instead of base/gcc by the original Makefile). It does work with either though. So If it's better to remove the line completely i am fine by that. Sorry about this.

**Comment by jrmarino** [comment]
Ok, it's pushed.
btw, there's not difference between GCC and BASE for dragonfly so we could have left it as gcc.

**Comment by dkgroot** [comment]
Ah ok. Thanks for the info ! Same will apply to the asterisk13 commit. Would you like me to update it ?

**Comment by dkgroot** [comment]
Thanks again for you help!

**Pull request merged**
