### PR TITLE
games/sauerbraten: fix build

### PR DESCRIPTION
**Pull request by zrj-rimwis**
Cool CUBE2 based FPS shooter game works great on haswell
Note: quite big 655M installed

### CODE REVIEW

**Comment by jrmarino** [comment]
655M is too big, this needs MANUAL_PACKAGE_BUILD set with the typical DPORTS BUILDER exception

**Comment by zrj-rimwis** [comment]
Honestly don't know how to deal with this one.
Single distfile contains both engine and data (563M).
Package .txz is 540M, installed 655M
Maybe we need some marker to build on muscles but ignore on pkgbox?
Or maybe even smth like PASSTHROUGH=yes that ignores build but includes in dports as is.
Would be usefeul for ports like p5-OpenGL too

**Comment by jrmarino** [comment]
"Maybe we need some marker to build on muscles but ignore on pkgbox?"

That's the the dports builder exception does.  Look at any of the huge -data ports.  You many have to set MANUAL_PACKAGE_BUILD in Makefile.DragonFly first.   (or set it if not DPORTS_BUILDER)

**Comment by jrmarino** [comment]
I'll add the filter.

**Comment by jrmarino** [comment]
ah, i missed that you already did!

**Pull request merged**
