### PR TITLE
graphics/cimg: fix build, by renaming CCVER

### PR DESCRIPTION
**Pull request by zrj-rimwis**
This one took some time to figure out.
Some examples work, others give:
X Error of failed request:  BadLength (poly request too large or internal Xlib length error)
Looks to be xorg+mesa issue, also some missing demo images.

### CODE REVIEW

**Comment by jrmarino** [comment]
are you saying there is a name clash with our CCVER in the environment?

**Comment by zrj-rimwis** [comment]
yup, they use CCVER= g++ etc
that gives exec -o failed

**Comment by jrmarino** [comment]
that's a new one ...

**Comment by zrj-rimwis** [comment]
yeah smth like 2h for me to understand what is going on,
manual commands work, but not from makefile :)

**Pull request merged**
