### PR TITLE
Fix cargo 0.11.0

### PR DESCRIPTION
**Pull request by mneumann**
This uses a new cargo snapshot I built, plus some minor fixes
(crate version of fs2 0.2.3 -> 0.2.5).

### CODE REVIEW

**Comment by jrmarino** [comment]
Hi Michael, 
We need a new cargo bootstrap, one that is statically built.

look what happens when the base openssl is not present (happens when NO_OPENSSL is set and will eventually be removed completely):

```
# ldd bin/cargo
bin/cargo:
        libcurl.so.4 => /usr/local/lib/libcurl.so.4 (0x800ef6000)
        libssh2.so.1 => /usr/local/lib/libssh2.so.1 (0x800f63000)
        libssl.so.8 => not found (0)
        libcrypto.so.8 => not found (0)
        libz.so.3 => /lib/libz.so.3 (0x800f90000)
        libpthread.so.0 => /usr/lib/libpthread.so.0 (0x800fa5000)
        libc.so.8 => /lib/libc.so.8 (0x800458000)
        libm.so.4 => /lib/libm.so.4 (0x800fbd000)
        libssl.so.39 => /usr/local/lib/libssl.so.39 (0x800fe6000)
        libcrypto.so.38 => /usr/local/lib/libcrypto.so.38 (0x801043000)
        libk5crypto.so.3.1 => /usr/local/lib/libk5crypto.so.3.1 (0x80121c000)
        libcom_err.so.3.0 => /usr/local/lib/libcom_err.so.3.0 (0x8005c9000)
        libkrb5.so.3.3 => /usr/local/lib/libkrb5.so.3.3 (0x80124e000)
        libgssapi_krb5.so.2.2 => /usr/local/lib/libgssapi_krb5.so.2.2 (0x801332000)
        libssp.so.0 => /usr/lib/gcc50/libssp.so.0 (0x8005cd000)
        libkrb5support.so.0.1 => /usr/local/lib/libkrb5support.so.0.1 (0x801382000)
        libintl.so.8 => /usr/local/lib/libintl.so.8 (0x80138e000)
```

besides the SSL libraries, all the libraries located in /usr/local/lib are liabilities.  Is it possible to get a static version of cargo made?

**Comment by mneumann** [comment]
how about building a snapshot of cargo that links to openssl/libressl package from ports? static linking is probably not that easy...

**Comment by jrmarino** [comment]
we're just kicking the can down the road.  Bootstraps should always be statically compiled for this reason.  any time a library version number changes, the bootstrap breaks.

Plus having multiple bootstraps depending on the build platform also seriously increases complexity.  You're talking about a minimum of 3, maybe even 5 bootstraps now (base, libressl, openssl, libressl-devel, openssl-devel).

unfortunately, bootstrapping is inherently "not that easy" and this is a typical issue.

**Comment by jrmarino** [comment]
now the new cargo 0.13 fails to patch.
It seems that every single new version of cargo requires maintenance.
Can you fix the patch the patch(es) for cargo 0.13(?)
also in a couple of weeks we may remove base openssl so effectively cargo will not longer be available on master and later, so the issue above is not going away.

**Comment by mneumann** [comment]
hm, I tried to build a static version, but my attempt failed. I will give cargo 0.13 a try. Locally, it built for me.
Does the version of cargo below help you (it's build against master w/ libressl):

```
mneumann@babel% /usr/local/bin/cargo --version
cargo 0.13.0 (9399229 2016-09-14)
mneumann@babel% ldd /usr/local/bin/cargo 
/usr/local/bin/cargo:
	libssh2.so.1 => /usr/local/lib/libssh2.so.1 (0x800d85000)
	libcurl.so.4 => /usr/local/lib/libcurl.so.4 (0x800db2000)
	libssl.so.39 => /usr/local/lib/libssl.so.39 (0x800e1f000)
	libcrypto.so.38 => /usr/local/lib/libcrypto.so.38 (0x800e7c000)
	libz.so.3 => /lib/libz.so.3 (0x801055000)
	libpthread.so.0 => /usr/lib/libpthread.so.0 (0x80106a000)
	libc.so.8 => /lib/libc.so.8 (0x800458000)
	libm.so.4 => /lib/libm.so.4 (0x801082000)
	libk5crypto.so.3.1 => /usr/local/lib/libk5crypto.so.3.1 (0x8010aa000)
	libcom_err.so.3.0 => /usr/local/lib/libcom_err.so.3.0 (0x8005c9000)
	libkrb5.so.3.3 => /usr/local/lib/libkrb5.so.3.3 (0x8010dc000)
	libgssapi_krb5.so.2.2 => /usr/local/lib/libgssapi_krb5.so.2.2 (0x8011c0000)
	libssp.so.0 => /usr/lib/gcc50/libssp.so.0 (0x8005cd000)
	libkrb5support.so.0.1 => /usr/local/lib/libkrb5support.so.0.1 (0x801210000)
	libintl.so.8 => /usr/local/lib/libintl.so.8 (0x80121c000)
```

**Comment by jrmarino** [comment]
it doesn't help, it just shifts the problem.  basically all the /usr/local/lib/* ones are an issue.  openssl* is the biggest issue, but curl, ssh, gssapi, are all problems in waiting.

**Comment by jrmarino** [comment]
One thought has been bugging me for a few days.  The decision to use cargo to build cargo seems absolutely asinine to me.   You have to expect to bootstrap rust, but everything else should be buildable from source.  I think I read that cargo needs cargo, but how true is this really?  It's a rust program right?  Why can't it be built from source?

**Comment by mneumann** [comment]
it can be built from source, but you have to specify all dependent versions from hand and download all of them etc. Also pass all correct arguments from hand. there was a python script that did exactly that. we used it to bootstrap the freebsd and dragonfly version of cargo.

**Comment by mneumann** [comment]
@jrmarino : I finally got some spare time to build a static version of cargo. You can download it from here: http://www.ntecs.de/downloads/rust/cargo-dfly-f6500c6b-2016-11-11.bz2. Uncompressed, the binary will have the following checksum:

    SHA256 (cargo-dfly-f6500c6b-2016-11-11) = ca155f7da529360eb51c9258af7f2b6a17298a48b820dec718d3bf2291676dd6

It's dependencies are:

```
# ldd ./cargo-dfly-f6500c6b-2016-11-11
./cargo-dfly-f6500c6b-2016-11-11:
	libpthread.so.0 => /usr/lib/libpthread.so.0 (0x800fc9000)
	libc.so.8 => /lib/libc.so.8 (0x800458000)
	libm.so.4 => /lib/libm.so.4 (0x800fe1000)
```

This is version 0.15.0 as of 2016-11-11 of cargo, built with OpenSSL 1.0.2j. I used the following script to build it: https://gist.github.com/mneumann/1997339bf559a688f220598bda2f6c93.

Please tell me if this helps to get the cargo package in dports working again.

**Comment by jrmarino** [comment]
@mneumann , great!  However I'm missing one thing.
On snapshot.txt , there needs to be an entry for 2016-11-11 / dragonfly-86_64, but I don't know hash to use there.

to clarify: I have to patch snapshot.txt otherwise the build fails like this:
```
--------------------------------------------------------------------------------
--  Phase: configure
--------------------------------------------------------------------------------
===>   cargo-0.13.0 depends on executable: cmake - found
===>   cargo-0.13.0 depends on package: rust>=1.5.0 - found
===>   cargo-0.13.0 depends on executable: gmake - found
===>   cargo-0.13.0 depends on file: /usr/local/bin/python2.7 - found
===>   cargo-0.13.0 depends on package: pkgconf>=0.9.10 - found
===>   cargo-0.13.0 depends on file: /usr/local/lib/libcrypto.so.9 - found
===>   cargo-0.13.0 depends on shared library: libssh2.so - found (/usr/local/lib/libssh2.so)
===>   cargo-0.13.0 depends on shared library: libcurl.so - found (/usr/local/lib/libcurl.so)
===>  Configuring for cargo-0.13.0
configure: looking for configure programs
configure: found cmp
configure: found mkdir
configure: found printf
configure: found cut
configure: found head
configure: found grep
configure: found xargs
configure: found cp
configure: found find
configure: found uname
configure: found date
configure: found tr
configure: found sed
configure: found cmake
configure: found curl
configure: recreating config.tmp
configure: 
configure: processing ./configure args
configure: 
configure: CFG_PREFIX           := /usr/local 
configure: CFG_LOCAL_RUST_ROOT  :=  
configure: CFG_RUSTC            := /usr/local/bin/rustc (rustc 1.12.1)
configure: CFG_BUILD            := x86_64-unknown-dragonfly 
configure: CFG_HOST             := x86_64-unknown-dragonfly 
configure: CFG_TARGET           := x86_64-unknown-dragonfly 
configure: CFG_LOCALSTATEDIR    := /var/lib 
configure: CFG_SYSCONFDIR       := /etc 
configure: CFG_DATADIR          := /usr/local/share 
configure: CFG_INFODIR          := /usr/local/share/info 
configure: CFG_DOCDIR           := /usr/local/share/doc/cargo 
configure: CFG_MANDIR           := /usr/local/man 
configure: CFG_LIBDIR           := /usr/local/lib 
configure: CFG_LOCAL_CARGO      :=  
configure: 
configure: validating ./configure args
configure: 
configure: 
configure: looking for build programs
configure: 
configure: CFG_PYTHON           := /usr/local/bin/python2.7 
configure: CFG_CC               := /usr/bin/cc (cc 5.4.1 [DragonFly] Release/2016-08-27)
configure: CFG_RUSTDOC          := /usr/local/bin/rustdoc (rustdoc 1.12.1)
configure: 
configure: writing configuration
configure: 
configure: CFG_SRC_DIR          := /construction/devel/cargo/cargo-0.1 ...
configure: CFG_BUILD_DIR        := /construction/devel/cargo/cargo-0.1 ...
configure: CFG_CONFIGURE_ARGS   := --prefix=/usr/local --mandir=/usr/l ...
configure: CFG_PREFIX           := /usr/local 
configure: CFG_BUILD            := x86_64-unknown-dragonfly 
configure: CFG_HOST             := x86_64-unknown-dragonfly 
configure: CFG_TARGET           := x86_64-unknown-dragonfly 
configure: CFG_DATADIR          := /share 
configure: CFG_DOCDIR           := /share/doc/cargo 
configure: CFG_INFODIR          := /share/info 
configure: CFG_MANDIR           := /man 
configure: CFG_LIBDIR           := /lib 
configure: CFG_RUSTC            := /usr/local/bin/rustc 
configure: CFG_RUSTDOC          := /usr/local/bin/rustdoc 
configure: 
configure: cp /construction/devel/cargo/cargo-0.13.0/Makefile.in ./Makefile
configure: mv config.tmp config.mk
configure: 
configure: complete
configure: 
configure: 



--------------------------------------------------------------------------------
--  Phase: build
--------------------------------------------------------------------------------
===>  Building for cargo-0.13.0
gmake[2]: Entering directory '/construction/devel/cargo/cargo-0.13.0'
/usr/local/bin/python2.7 /construction/devel/cargo/cargo-0.13.0//src/etc/dl-snapshot.py x86_64-unknown-dragonfly
Traceback (most recent call last):
  File "/construction/devel/cargo/cargo-0.13.0//src/etc/dl-snapshot.py", line 58, in <module>
    raise Exception("no snapshot for the triple '%s'" % triple)
Exception: no snapshot for the triple 'x86_64-unknown-dragonfly'
gmake[2]: *** [Makefile:107: target/snapshot/bin/cargo] Error 1
gmake[2]: Leaving directory '/construction/devel/cargo/cargo-0.13.0'
===> Compilation failed unexpectedly.
Try to set MAKE_JOBS_UNSAFE=yes and rebuild before reporting the failure to
the maintainer.
*** Error code 1
```

**Comment by mneumann** [comment]
@jrmarino See https://github.com/DragonFlyBSD/DeltaPorts/pull/651

**Comment by mneumann** [comment]
@jrmarino btw, I used [this](https://gist.github.com/mneumann/2c86078a8c99d6e325fd70d26608dfa8) to build the snapshot (.tar.gz). The checksum in snapshot.txt is a SHA1 checksum of the .tar.gz produced in ```target/x84_64-unknown-dragonfly/release/dist``` (which contains some additional files, not just the binary).

**Pull request merged**
