### PR TITLE
editors/fileobj: test port of tkusumi hexeditor

### PR DESCRIPTION
**Pull request by zrj-rimwis**
has issues at runtime if devel/ncurses is installed

### CODE REVIEW

**Comment by jrmarino** [comment]
i would prefer to commit this directly to ports.

**Comment by jrmarino** [comment]
congratulations on your first port!
http://www.freshports.org/editors/fileobj/

**Comment by jrmarino** [comment]
although looking at it again, maybe we could have used autoplist instead of pkg-plist

**Comment by jrmarino** [comment]
it's in dports now

**Comment by jrmarino** [comment]
I think you gave a bum email address.  And fileobj has already been updated to the next version.
What valid email address do you want to use?
see below.

I was about to reset MAINTAINER on this, but realized it was added
to the tree yesterday.

Can you verify the email address is correct?

-r

----- Forwarded message from Mail Delivery System <MAILER-DAEMON@mx2.freebsd.org> -----

Date: Sun, 17 Jan 2016 08:41:49 +0000 (UTC)
From: Mail Delivery System <MAILER-DAEMON@mx2.freebsd.org>
To: portscout@FreeBSD.org
Subject: Undelivered Mail Returned to Sender

This is the mail system at host mx2.freebsd.org.

I'm sorry to have to inform you that your message could not
be delivered to one or more recipients. It's attached below.

For further assistance, please send mail to postmaster.

If you do so, please include this problem report. You can
delete your own text from the attached returned message.

                  The mail system

<zrj@ef.irc>: Host or domain name not found. Name service error for name=ef.irc
   type=AAAA: Host not found

Reporting-MTA: dns; mx2.freebsd.org
X-Postfix-Queue-ID: B27D96B470
X-Postfix-Sender: rfc822; portscout@FreeBSD.org
Arrival-Date: Sun, 17 Jan 2016 08:41:48 +0000 (UTC)

Final-Recipient: rfc822; zrj@ef.irc
Original-Recipient: rfc822;zrj@ef.irc
Action: failed
Status: 5.4.4
Diagnostic-Code: X-Postfix; Host or domain name not found. Name service error
   for name=ef.irc type=AAAA: Host not found

Date: Sun, 17 Jan 2016 08:41:48 +0000
From: portscout@FreeBSD.org
To: zrj@ef.irc
Subject: FreeBSD ports you maintain which are out of date

Dear port maintainer,

The portscout new distfile checker has detected that one or more of your
ports appears to be out of date. Please take the opportunity to check
each of the ports listed below, and if possible and appropriate,
submit/commit an update. If any ports have already been updated, you can
safely ignore the entry.

You will not be e-mailed again for any of the port/version combinations
below.

Full details can be found at the following URL:
http://portscout.freebsd.org/zrj@ef.irc.html


Port                                            | Current version | New version
------------------------------------------------+-----------------+------------
editors/fileobj                                 | 0.7.23.1        | v0.7.25
------------------------------------------------+-----------------+------------


If any of the above results are invalid, please check the following page
for details on how to improve portscout's detection and selection of
distfiles on a per-port basis:

http://portscout.freebsd.org/info/portscout-portconfig.txt

Thanks.

**Comment by zrj-rimwis** [comment]
ah this PR got lost between my other emails and  thought it was merged just to dports.
Yeah that email is bogus, mostly to reduce spam (shows up in public lists and bots quickly gather them)
i mostly added this port to debug issue when devel/ncurses is installed and breaks python-ncurses

**Comment by jrmarino** [comment]
okay, but we need a real address though, one that you'll get notices like what was attempted here

**Comment by jrmarino** [comment]
can you provide a patch that will update fileobj to the latest version and fix the maintainer email at the same time?  Then I will update ports directly.

**Comment by zrj-rimwis** [comment]
currently i have this: http://sprunge.us/AFTW
thanks for autoplist hint, pkg-plist is no longer required

**Comment by jrmarino** [comment]
strange, corporate file blocks sprunge, pastie, pastebin.... weird.

**Comment by kusumi** [comment]
wow!  thanks to both of you for pushing my code into freebsd/ports  > zrj & marino

**Comment by jrmarino** [comment]
hmm, i finally see the sprung but the email address was not updated.  We *have* to update it.

**Comment by jrmarino** [comment]
i used dragonflybsd.org

**Pull request closed without merging**
