### PR TITLE
D1507 fix graphics

### PR DESCRIPTION
**Pull request by zrj-rimwis**
Fix for flightgear included
multimedia/avidemux-plugins fails to build with mp4 format support

### CODE REVIEW

**Comment by jrmarino** [comment]
gstream1-plugins-gl has about 80 errors, similar to:

**Comment by jrmarino** [comment]
In file included from ../../../gst-libs/gst/gl/gstgl_fwd.h:26:0,
                 from gl.h:29,
                 from gstgldisplay.c:56:
../../../gst-libs/gst/gl/glprototypes/base.h:52:23: error: unknown type name 'GLenum'
                      (GLenum target, GLuint texture))

**Comment by zrj-rimwis** [comment]
for some reason it doesn't pick up substitution in multimedia/gstreamer1-plugins/Makefile.Dragonfly
but it builds fine for me locally in dports

**Comment by jrmarino** [comment]
check the makefile for ".include" e.g. MASTERDIR or .CURDIR/../../

if that is present, then it's pulling in the Makefile.DragonFly from that location.
In these cases, it's sometimes better just to use a diff, but each case is unique.

**Comment by zrj-rimwis** [comment]
cannot reproduce breakage locally
easiest way would be to upstream typo fix to gstreamer1 git repo

**Comment by jrmarino** [comment]
The problem was just as I guessed it was.
So was the fix: ff76fa45f04a597fc93b0247add8e95d176f519f

**Pull request merged**
