### PR TITLE
graphics/cal3d: fix memcpy/memset decl issue

### PR DESCRIPTION
**Pull request by zrj-rimwis**
cal3d tests:
  PASS: converter/skeleton
  PASS: converter/mesh
  PASS: converter/material
  PASS: converter/animation
  ==================
  All 4 tests passed
  ==================

cal3d-devel: unchecked(tests/Makefile gen issue)

### CODE REVIEW

**Comment by zrj-rimwis** [comment]
Next try:
graphics/py-soya3d (everything I tested works)

Builds but:
games/balazar (works without sound, but problems with OGG streams), py-soya3d is fine with audio
games/balazarbrothers (no sound, not a big issue)
games/el (works but cannot connect to server, too old version - 193, needed 194)
games/slune (wrongly packaged or don't get it how to invoke it, also gettext.localisation(..).intstal(1) problem)

**Comment by jrmarino** [comment]
can you resubmit without the ifdef __DragonFly condition?  just include <string.h> unconditionally.  This is something that can be pushed upstream.

**Comment by jrmarino** [comment]
don't bother, i'll just commit to ports.

**Comment by jrmarino** [comment]
Fixed upstream, pull request obsolete.

**Pull request closed without merging**
