### PR TITLE
Bring in Cargo - Rust's package manager.

### PR DESCRIPTION
**Pull request by mneumann**

### CODE REVIEW

**Comment by jrmarino** [comment]
On the next update, you can just add DragonFly's entry to distinfo rather than replacing freebsd's entry

**Comment by jrmarino** [comment]
This doesn't build.
````
=======================<phase: patch-depends  >============================
===========================================================================
=======================<phase: patch          >============================
===>  Patching for cargo-0.4.0.20150720
cd /wrkdirs/devel/cargo/work/cargo-9c5ffcb871/.. && git clone https://github.com/carllerche/curl-rust.git
/bin/sh: git: not found
*** Error code 127

Stop.
make[1]: stopped in /usr/ports/devel/cargo
*** Error code 1
```
http://muscles.dragonflybsd.org/bulk/bleeding-edge-potential/20150914_014157/logs/errors/cargo-0.4.0.20150720.log

**Comment by mneumann** [comment]
ok, add distinfo. Needs git. Will fix.

**Comment by jrmarino** [comment]
The new version 0.7 is out and the patches need to be regenerated

**Comment by jrmarino** [comment]
see http://www.freshports.org/devel/cargo

**Comment by jrmarino** [comment]
mneumann, have you had a chance to look at this?

**Pull request merged**
