### PR TITLE
Added asterisk13

### PR DESCRIPTION
**Pull request by dkgroot**

### CODE REVIEW

**Comment by jrmarino** [comment]
what about diffs/Makefile.diff ?

see asterisk11

**Comment by dkgroot** [comment]
Hi jrmarino,
I overlooked that one yesterday. Added it now though.

**Comment by jrmarino** [comment]
It doesn't build.  the dragonfly/patch-chan_skinny.c patch fails to apply.

**Comment by dkgroot** [comment]
Huh.. I thought i had removed that patch (not required in asterisk13)... I am messing things up.

**Comment by jrmarino** [comment]
ok I'll remove it.

**Comment by dkgroot** [comment]
Sorry about this.

**Comment by jrmarino** [comment]
Now the dfly-patch target fails.  See http://muscles.dragonflybsd.org/bulk/bleeding-edge-potential/20151106_025458/logs/errors/asterisk13-13.6.0.log

**Comment by dkgroot** [comment]
I accidentally took a copy from an old version of asterisk13, which i had been working on during testing. I know what to fix, but am not sure what would be the best way to provide the fix to you.

<pre>
--- /usr/DeltaPorts/ports/net/asterisk13/Makefile.DragonFly	2015-11-05 18:10:57.230401000 +0100
+++ Makefile.DragonFly	2015-11-06 12:02:57.784721000 +0100
@@ -3,7 +3,7 @@
 		-e 's@\(#if !defined(__FreeBSD__)\)@\1 \&\& !defined(__DragonFly__)@g			\
 		-e 's@\( defined(__FreeBSD__)\)@\1 || defined(__DragonFly__)@g'				\
 		-e 's@ifdef __FreeBSD__@if defined(__FreeBSD__) || defined(__DragonFly__)@g'		\
-		-e 's@ifndef __FreeBSD__@if !defined(__FreeBSD__) \&\& !defined(__DragonFly__)@g'	\
+		-e 's@ifndef __FreeBSD__@if !defined(__FreeBSD__) && !defined(__DragonFly__)@g'		\
 		${WRKSRC}/channels/chan_sip.c								\
 		${WRKSRC}/channels/chan_dahdi.c								\
 		${WRKSRC}/channels/chan_oss.c								\
</pre>

**Comment by dkgroot** [comment]
I will try and go a little slower on the next pull request. Little annoyed with myself at the moment.

**Comment by jrmarino** [comment]
just start with current version of dports and modify what is necessary.  maybe a new pull request, not sure.  Just something I can merge via github.

**Comment by jrmarino** [comment]
correction: deltaports

**Comment by dkgroot** [comment]
Ok Perfect i will do that. 
Is there a simple way a run a DeltaPort generation for asterisk13 only (locally ?) So i can do a full test before submitting. Just to prevent these issues happening ?

**Comment by jrmarino** [comment]
there's a scripts/generator/sync.1 script that will do it but it needs to have a config file I think (it needs a location for *FREEBSD* ports too.

**Comment by jrmarino** [comment]
for 1 port it may be easier to do it manually esp. if there is no ${ARCH} in the makefile

**Comment by dkgroot** [comment]
Ok, thanks for your help. Sorry this is taking so much of your time.

**Pull request merged**
