### PR TITLE
fix recent broken patches for CRLF

### PR DESCRIPTION
**Pull request by zrj-rimwis**
Use DOS2UNIX

### CODE REVIEW

**Comment by zrj-rimwis** [comment]
correct? should i revert previous repush of LF->CRLF in patches and change to use DOS2UNIX too?

also try building misc/seabios (gcc4.8 and forced lf.bfd otherwise doesn't build)

**Comment by zrj-rimwis** [comment]
there are more dragonfly patches that has CRLF: http://sprunge.us/LciK
so leave them for now, or convert to DOS2UNIX_FILES ?

**Comment by jrmarino** [comment]
i prefer DOS2UNIX always, so it's a good change as far as I am concerned

**Comment by jrmarino** [comment]
i would leave anything that works and change it only when the patches need to be regenerated.  no need to do extra work.

**Pull request merged**
