### PR TITLE
security/cyrus-sasl2-gssapi: Work around messy heimdal.

### PR DESCRIPTION
**Pull request by zrj-rimwis**
I think it is just better to use GSSAPI_MIT here.
Nothing depends on this lib.

### CODE REVIEW

**Comment by jrmarino** [comment]
".if 1" evaluates to zero?  
Isn't that kind of misleading?

**Comment by zrj-rimwis** [comment]
i think it works as expecting .if 1 - > true, .if 0 -> false

**Comment by jrmarino** [comment]
then the commit doesn't match the description.  You've kept heimdal, not switched to MIT

**Comment by jrmarino** [comment]
i changed the option manually, PR is now obsolete.
Oh, I didn't realize I closed the PR already.  I wanted to close it now though.

**Pull request closed without merging**
