### PR TITLE
devel/cmake: For a rainy day.

### PR DESCRIPTION
**Pull request by zrj-rimwis**

### CODE REVIEW

**Comment by jrmarino** [comment]
cmake 3.9.0 is out (it's only a matter of time before it hits freebsd ports, and it's already in ravenports).  It's possible these patches won't apply to the next release of cmake.

**Comment by zrj-rimwis** [comment]
oh ports cmake is really stale, so will wait for updated one

**Comment by zrj-rimwis** [comment]
Just line differences, patches apply cleanly.

**Comment by jrmarino** [comment]
let's hope it still applies to 3.8.2 because I don't know how long it will take freebsd to upgrade.  they probably have to execute exp_runs.

**Pull request merged**
