### PR TITLE
Added asterisk13

### PR DESCRIPTION
**Pull request by dkgroot**
Added asterisk-13.6.0 based on FreePBX ports

### CODE REVIEW

**Comment by jrmarino** [comment]
can you resubmit based on the changes I made to asterisk11 ?

**Comment by dkgroot** [comment]
Ok I will !

**Comment by jrmarino** [comment]
ah, this has never built.
The build system adds and modifies STATUS, it will be created automatically.  By pushing it, you are showing false information (e.g. that it built successfully in the past which is untrue)

**Comment by dkgroot** [comment]
We can drop this pull request. I will resubmit, after rebasing.

**Pull request closed without merging**
