### PR TITLE
D1507 fix pack tcl tk

### PR DESCRIPTION
**Pull request by zrj-rimwis**
simple changes for compilation of Tk/Tcl

### CODE REVIEW

**Comment by jrmarino** [comment]
My laptop drive crashed 1 day before the whole laptop was supposed to be replaced (was already set for data transfer).  I lost access to my private key so I can't build these for a day or so.

**Comment by jrmarino** [comment]
tclbsd failed:
cd /wrkdirs/devel/tclbsd/work/tclbsd-1.6 ; autoconf # needed to gen configure first
/bin/sh: autoconf: not found
*** Error code 127

yajl-tcl failed:
===>  Patching for yajl-tcl-1.6
cd /wrkdirs/devel/yajl-tcl/work/yajl-tcl-1.6 ; autoconf # needed to gen configure first
/bin/sh: autoconf: not found
*** Error code 127

**Comment by zrj-rimwis** [comment]
for some reason USE_AUTOTOOLS= autoconf doesn't work or i missunderstood how to invoke autotools

**Comment by zrj-rimwis** [comment]
ah i think i got the idea
it works if i change target: dfly-patch -> run-autotools-fixup but that is a bit too hack-ish

**Comment by jrmarino** [comment]
i assume the problem is that you invoke autotools, but autotools is not a listed dependency.  (thus not available within poudriere jail)

**Comment by jrmarino** [comment]
i didn't look though, I just assumed that was the cause of the issue.

**Pull request merged**
