### PR TITLE
games/ufoai: Fix for data extract

### PR DESCRIPTION
**Pull request by zrj-rimwis**
Data is bigish ~1GB
Game runs, playing is fine on i915 haswell

### CODE REVIEW

**Comment by jrmarino** [comment]
NO_WRKSUBDIR is set in the makefile so this line has no effect.

This port was building fine before, it shouldn't need anything other than removing the ignore.

**Comment by zrj-rimwis** [comment]
huh, then it gets somehow unset?

**Comment by jrmarino** [comment]
no.  It should be working fine.  Are you using a clean poudriere build?  WRKDIR stuff changed a few weeks ago.  You have to have the last tree.

**Comment by jrmarino** [comment]
if you remove the WRKDIR redefinition from MD, I'll merge it in.  I'm confident it it work.

**Comment by jrmarino** [comment]
fixed a different way (a way that should be upstreamed)

**Pull request closed without merging**
